home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    # path('', views.UserThemeSetClassView.as_view(), name='user-theme')
]

master_petugas/urls.py
from django.urls import path
from . import views

app_name = 'master_petugas'

urlpatterns = [
    path('master-petugas', views.MasterPetugasClassView.as_view(), name='index'),
    path('master-petugas/json-response', views.MasterPetugasJsonResponseClassView.as_view(), name='datatable-json'),
    path('master-petugas/delete', views.MasterPetugasDeleteView.as_view(), name='delete-petugas'),
    path('master-petugas/detail', views.MasterPetugasDetailView.as_view(), name='detail'),
    path('master-petugas/update', views.MasterPetugasUpdateView.as_view(), name='update'),
    path('master-petugas/upload', views.MasterPetugasUploadClassView.as_view(), name="upload-petugas"),
    path('master-petugas/export', views.MasterPetugasExportClassView.as_view(), name="mitra-export"),
    path('master-petugas/template/<int:rows>', views.MasterPetugasTemplateClassView.as_view(), name="mitra-template"),
    path('master-petugas/view-petugas/<int:mitra_id>', views.MasterPetugasDetailViewClassView.as_view(), name="mitra-view-detail"),
    path('master-petugas/search', views.MasterPetugasSearchClassView.as_view(), name="mitra-search"),
          

    path('alokasi-petugas', views.AlokasiPetugasClassView.as_view(), name='alokasi'),
    path('alokasi-petugas/json-response', views.MasterAlokasiJsonResponseClassView.as_view(), name='datatable-json-alok'),
    path('alokasi-petugas/delete', views.AlokasiPetugasDeleteView.as_view(), name='delete-alokasi'),
    path('alokasi-petugas/detail', views.MasterAlokasiDetailView.as_view(), name='detail-alokasi'),
    path('alokasi-petugas/update', views.MasterAlokasiUpdateView.as_view(), name='update-alokasi'),
    path('alokasi-petugas/export', views.MasterAlokasiExportClassView.as_view(), name='export-alokasi'),
    path('alokasi-petugas/upload', views.MasterAlokasiUploadClassView.as_view(), name="upload-alokasi"),
    path('alokasi-petugas/template/<int:rows>', views.MasterAlokasiTemplateClassView.as_view(), name="template-alokasi"),
    
    
    path('role-petugas', views.RolePetugasClassView.as_view(), name='role'),
    path('role-petugas/json-response', views.MasterRoleJsonResponseClassView.as_view(), name='datatable-json-role'),
    path('role-petugas/delete', views.RolePetugasDeleteView.as_view(), name='delete-role'),
    path('role-petugas/detail', views.MasterRoleDetailView.as_view(), name='detail-role'),
    path('role-petugas/update', views.MasterRoleUpdateView.as_view(), name='update-role'),
    path('role-petugas/export', views.MasterRoleExportClassView.as_view(), name='export-role'),

]

munapps/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('authentication.urls')),
    # path('', include('home.urls')),
    
    path('', include('dashboard.urls')),
    path('', include('master_penilaian.urls')),
    path('', include('master_petugas.urls')),
    path('', include('master_survey.urls')),
    
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

master_petugas/models.py
from django.db import models
from master_survey.models import SurveyModel
from .validators import int_validators

# Create your models here.
class MasterPetugas(models.Model):

    status_choices = (
       ('0', 'Aktif'), ('1', 'Non Aktif'), ('2', 'Organik'), ('3', 'Blacklist')
    )

    pendidikan = (
       ('0', 'SD/MI Sederajat'), 
       ('1', 'SMP/SLTP Sederajat'),
       ('2', 'SMA/SLTA Sederajat'),
       ('3', 'DI-DIII'),
       ('4', 'DV/S1'),
       ('5', 'S2'),
       ('6', 'S3')
    )
    

    agama = (
       ('0', 'Islam'), 
       ('1', 'Kristen'),
       ('2', 'Hindu'),
       ('3', 'Budha'),
    )

    kode_petugas = models.CharField(max_length=16, null=False, blank=False, unique=True, verbose_name='Kode Petugas/ID Sobat')
    nama_petugas = models.CharField(max_length=64, null=False, blank=False,  verbose_name='Nama Petugas')
    nik = models.CharField(max_length=16, null=False, blank=False, validators=[int_validators], unique=True, verbose_name='NIK')
    npwp = models.CharField(max_length=15, null=False, blank=False, validators=[int_validators], unique=True, verbose_name='NPWP')
    tgl_lahir = models.DateField(auto_now=False, auto_now_add=False, null=False, blank=False, verbose_name='Tanggal Lahir')
    pendidikan = models.CharField(max_length=1, choices=pendidikan, null=False, blank=False, verbose_name='Pendidikan Terakhir')
    pekerjaan = models.CharField(max_length=128, null=False, blank=False, verbose_name='Pekerjaan')
    agama = models.CharField(max_length=1, choices=agama, null=False, blank=False, verbose_name='Agama')
    email = models.EmailField(max_length=128, null=False, blank=False,unique=True, verbose_name='Email')
    no_telp = models.CharField(max_length=13, null=False, blank=False, validators=[int_validators], verbose_name='No. Telp')
    alamat = models.CharField(max_length=256, null=False, blank=False, verbose_name='Alamat Domisili')
    
    status = models.CharField(max_length=1, choices=status_choices, blank=False, verbose_name='Status Mitra')
    
    def __str__(self):
        return f"{self.nama_petugas} [{self.kode_petugas}]"

class RoleMitra(models.Model):
   jabatan = models.CharField(max_length=128, null=False, blank=False, verbose_name='Jabatan/Peran')
   def __str__(self):
         return f"{self.jabatan}"
   

class AlokasiPetugas(models.Model):

   petugas = models.ForeignKey(MasterPetugas, on_delete=models.RESTRICT, related_name='master_alokasi_petugas', verbose_name='Kode Petugas')
   survey = models.ForeignKey(SurveyModel, on_delete=models.RESTRICT, related_name='master_alokasi_survey', verbose_name='Survei/Sensus')
   role = models.ForeignKey(RoleMitra, on_delete=models.RESTRICT, related_name='master_alokasi_role', verbose_name='Jabatan Petugas')

   def __str__(self):
      return f"{self.petugas.nama_petugas} [{self.petugas.kode_petugas} - {self.survey.nama}_{self.role.jabatan}]"
   

master_petugas/views.py
import json
from django.urls import reverse, reverse_lazy
from django.core.serializers.json import DjangoJSONEncoder

from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.shortcuts import render
from django.views import View
from django.core import serializers
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from . import models, forms, utils

import itertools

from .resources import MasterPetugasResource, MasterAlokasiResource, MasterRoleResource
from master_survey.models import SurveyModel
from master_penilaian.models import MasterNilaiPetugas, KegiatanPenilaianModel

import numpy as np
from openpyxl import Workbook
from openpyxl.styles import Alignment
from openpyxl.styles import Font, PatternFill
from . import utils


from statistics import mean
from operator import itemgetter
from django.shortcuts import redirect

from pprint import pprint 
# Packages for upload master petugas

# Create your views here.

class MasterPetugasJsonResponseClassView(LoginRequiredMixin, View):

    def post(self, request):    
        data_wilayah = self._datatables(request)
        return HttpResponse(json.dumps(data_wilayah, cls=DjangoJSONEncoder), content_type='application/json')
		
    def _datatables(self, request):
        datatables = request.POST
        
        # Get Draw
        draw = int(datatables.get('draw'))
        start = int(datatables.get('start'))
        length = int(datatables.get('length'))
        page_number = int(start / length + 1)

        search = datatables.get('search[value]')

        order_idx = int(datatables.get('order[0][column]')) # Default 1st index for
        order_dir = datatables.get('order[0][dir]') # Descending or Ascending
        order_col = 'columns[' + str(order_idx) + '][data]'
        order_col_name = datatables.get(order_col)

        if (order_dir == "desc"):
            order_col_name =  str('-' + order_col_name)


        data = models.MasterPetugas.objects
        if datatables.get('pendidikan_filter'):
            data = data.filter(pendidikan = datatables.get('pendidikan_filter'))

        if datatables.get('status_filter'):
            data = data.filter(status = datatables.get('status_filter'))

        data = data.all().exclude(Q(kode_petugas=None)|Q(nama_petugas=None)|Q(nik=None)|Q(email=None)|Q(no_telp=None)|Q(status=None))
        records_total = data.count()
        records_filtered = records_total
        
        if search:

            data = models.MasterPetugas.objects

            if datatables.get('pendidikan_filter'):
                data = data.filter(pendidikan = datatables.get('pendidikan_filter'))

            if datatables.get('status_filter'):
                data = data.filter(status = datatables.get('status_filter'))

            data = data.filter(
                Q(kode_petugas__icontains=search)|
                Q(nama_petugas__icontains=search)|
                Q(nik__icontains=search)|
                Q(email__icontains=search)|
                Q(no_telp__icontains=search)|
                Q(status__icontains=search)
            ).exclude(Q(nama_petugas=None)|Q(nik=None)|Q(email=None)|Q(no_telp=None)|Q(status=None))

          
            records_total = data.count()
            records_filtered = records_total
        
        data = data.order_by(order_col_name)
        # Conf Paginator
        paginator = Paginator(data, length)

        try:
            object_list = paginator.page(page_number).object_list
        except PageNotAnInteger:
            object_list = paginator.page(1).object_list
        except EmptyPage:
            object_list = paginator.page(1).object_list

        data = []

        for obj in object_list:
            
            if obj.status == '0':
                class_badge = 'badge badge-success-lighten'
            elif obj.status == '1':
                class_badge = 'badge badge-secondary-lighten'
            elif obj.status == '3':
                class_badge = 'badge badge-danger-lighten'
            else:
                class_badge = 'badge badge-primary-lighten'

            data.append({
                        'kode_petugas': obj.kode_petugas,
                        'nama_petugas': f'<a href="{reverse_lazy("master_petugas:mitra-view-detail", kwargs={"mitra_id": obj.id})}" class="text-body">{obj.nama_petugas}</a>',
                        'nik': obj.nik,
                        'email': obj.email,
                        'no_telp': obj.no_telp,
                        'status': f'<span class="badge {class_badge}"> {obj.get_status_display()} </span>',
                        'aksi': f'<a href="javascript:void(0);" onclick="editPetugas({obj.id})" class="action-icon"><i class="mdi mdi-square-edit-outline"></i></a> <a href="javascript:void(0);" onclick="hapusPetugas({obj.id});" class="action-icon"> <i class="mdi mdi-delete"></i></a>'
                })
            
        return {
            'draw': draw,
            'recordsTotal': records_total,
            'recordsFiltered': records_filtered,
            'data': data,
        }


class MasterPetugasClassView(LoginRequiredMixin, View):

    data_petugas = models.MasterPetugas.objects

    def post(self, request):

        is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'
        if is_ajax:
            form = forms.MasterPetugasForm(request.POST)

            if form.is_valid():
                instance = form.save()
                ser_instance = serializers.serialize('json', [ instance, ])
                
                # send to client side.
                return JsonResponse({"instance": ser_instance, 'message': 'Data berhasil ditambahkan'}, status=200)
            else:
                return JsonResponse({"error": form.errors}, status=400)
        return JsonResponse({"error": ""}, status=400)


    def get(self, request):

        form = forms.MasterPetugasForm()
        context = {
            'title' : 'Master Mitra',
            'data_petugas' : self.data_petugas.all(),
            'form': form,
            'form_upload': forms.MasterPetugasFormUpload()
            }

        return render(request, 'master_petugas/index.html', context)


class MasterPetugasDeleteView(LoginRequiredMixin, View):

    def post(self, request):
        is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'

        if is_ajax:
            if request.method == 'POST':
                
                id = request.POST.get('id')

                data_petugas = models.MasterPetugas.objects.filter(pk = id)
                if data_petugas.exists():

                    check_nilai_mitra = MasterNilaiPetugas.objects.filter(petugas__petugas = id)
                    if check_nilai_mitra.exists():
                        return JsonResponse({'status' : 'failed', 'message': 'Data alokasi petugas telah digunakan pada master data penilaian'}, status=200)

                    data_petugas.delete()
                    return JsonResponse({'status' : 'success', 'message': 'Data berhasil dihapus'}, status=200)
                else:
                    return JsonResponse({'status': 'failed', 'message': 'Data tidak tersedia'}, status=200)
                
        return JsonResponse({'status': 'Invalid request'}, status=400)


class MasterPetugasDetailView(LoginRequiredMixin, View):


    def post(self, request):
        is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'

        if is_ajax:
            if request.method == 'POST':
                
                id = request.POST.get('id')
                data_petugas = models.MasterPetugas.objects.filter(pk=id)

                if data_petugas.exists():
                    return JsonResponse({'status' : 'success', 'instance': list(data_petugas.values())[0]}, status=200)
                else:
                    return JsonResponse({'status': 'failed', 'message': 'Data tidak tersedia'}, status=200)
                
        return JsonResponse({'status': 'Invalid request'}, status=400) 


class MasterPetugasUpdateView(LoginRequiredMixin, View):
    data_petugas = models.MasterPetugas.objects

    def post(self, request):
        is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'
        if is_ajax:

            data = get_object_or_404(models.MasterPetugas, pk=request.POST.get('id'))

            form = forms.MasterPetugasForm(request.POST, instance=data)

            if form.is_valid():
                instance = form.save()
                ser_instance = serializers.serialize('json', [ instance, ])
                
                # send to client side.
                return JsonResponse({"instance": ser_instance, 'message': 'Data berhasil diubah'}, status=200)
            else:
                return JsonResponse({"error": form.errors}, status=400)
        return JsonResponse({"error": ""}, status=400)


class MasterPetugasExportClassView(LoginRequiredMixin, View):
    def get(self, request):
    
        resource = MasterPetugasResource()
        dataset = resource.export()

        response = HttpResponse(dataset.xls, content_type='application/vnd.ms-excel')
        response['Content-Disposition'] = 'attachment; filename="Master Petugas.xls"'
        return response 
    

class MasterPetugasTemplateClassView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs): 

        def_rows = self.kwargs['rows']
        wb = Workbook()

        ws = wb.active

        # Ini untuk header columns
        ws.title = 'Upload Data Petugas'

        header = utils.get_verbose_fields(models.MasterPetugas, exclude_pk=True)
        header = ['No'] + header

        head_row = 2
        header_cols = np.array(ws[f'A{head_row}':f'M{head_row}'])

        # Set value and style for header
        for v,c in zip(header, header_cols.T.flatten()):

master_petugas/templates/master_petugas/role.html
{% extends 'base/detached-layout/datables.html' %}

{% load static %}

{% block nav_content %}
<!-- start page title -->
<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="javascript: void(0);">Manajemen Mitra</a></li>
                    <li class="breadcrumb-item active">Role Mitra</li>
                </ol>
            </div>
            <h4 class="page-title">{{title}}</h4>
        </div>
    </div>  
</div>     

{% endblock nav_content %}

{% block table-content %}
<div class="row">
    <div class="col-12">
        <div class="alert alert-danger d-none" id="msgs-upload" role="alert">   
           
            <div id="messages-content">
             
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                
                <h4 class="header-title">Jabatan Petugas</h4>
                <p class="text-muted font-14">
                    Tambahkan jabatan/role petugas untuk setiap jenis kegiatan pendataan lapangan dan pengolahan. 
                </p>
  
                <ul class="nav nav-tabs nav-bordered mb-3">
                      <li class="nav-item">
                          <a href="#rolepetugas-preview" data-bs-toggle="tab" aria-expanded="false" class="nav-link active">
                              Preview
                          </a>
                      </li>
                      <li class="nav-item">
                          <a href="#input-tab" data-bs-toggle="tab" aria-expanded="true" class="nav-link">
                              Input
                          </a>
                      </li>
                </ul> <!-- end nav-->
                <div class="tab-content">
                      <div class="tab-pane show active" id="rolepetugas-preview">
                            <div class="row mb-2">
                                <div class="col-md">
                                    <div class="text-sm-start">
                                        <button type="button" class="btn btn-success mb-2 me-1" id="redraw-table"><i class="mdi mdi-refresh"></i> Refresh</button>
                                        <a href="{% url 'master_petugas:export-role' %}" class="btn btn-light mb-2">Export</a>
                                    </div>
                                </div><!-- end col-->
                            </div>

                            <div class="table-responsive mt-3">
                                <table id="basic-datatable" class="table table-centered table-hover w-100 dt-responsive nowrap">
                                    <thead>
                                        <tr>
                                            <th>Jabatan/Role</th>
                                            <th class="text-center">Aksi</th>
                                        </tr>
                                    </thead>
                                
                                    <tbody>
    
                                    </tbody>
                                </table>                                            
                            </div>
                      </div> <!-- end preview-->
                
                      <div class="tab-pane" id="input-tab">
                          <p>Silahkan isikan Role Peserta.</p>
                          <form action="{% url 'master_petugas:role' %}" method="POST" id="formRolePetugas" class="needs-validation" novalidate>
                            {% csrf_token %}
                            <input type="hidden" name="id" id="id_id">
                            <div class="row mt-3">
                                <div class="col-lg-6">
                                    <h5 class="mb-3">{{ form.jabatan.label }}</h5>
                                    <div class="form-floating errors" id="form_{{form.jabatan.id_for_label}}">
                                        {{form.jabatan}}
                                        <label for="{{form.jabatan.id_for_label}}">{{ form.jabatan.label }}</label>
                                        <div class="invalid-feedback" id="msg-{{form.jabatan.id_for_label}}">
                                        </div>
                                    </div>
                            
                                </div>
                            </div>
                            <br>
                            <div class="row mt-2">
                                <div class="col-lg">        
                                     <button type="submit" class="btn btn-primary" id="submitformRolePetugas">Kirim Data</button>
                                     <button type="button" class="btn btn-primary" id="ResetformRolePetugas">Reset</button>
                                </div>
                            </div>
                        
                        </form>
                      </div> <!-- end preview code-->
                </div> <!-- end tab-content-->
  
            </div> <!-- end card body-->
        </div> <!-- end card -->
    </div><!-- end col-->
  </div>
  <!-- end row-->
  


<!-- Success Alert Modal -->
<div id="success-alert-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content modal-filled bg-success">
            <div class="modal-body p-4">
                <div class="text-center">
                    <i class="dripicons-checkmark h1"></i>
                    <h4 class="mt-2">Well Done!</h4>
                    <p class="mt-3 message-feedback"></p>
                    <button type="button" class="btn btn-light my-2" data-bs-dismiss="modal">Continue</button>
                </div>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


{% endblock table-content %}

{% block tables-script-extend %}

<script>
    var swalWithBootstrapButtons = Swal.mixin({
        customClass: {
          confirmButton: 'btn btn-primary'},
        buttonsStyling: true
    })

    var table = $("#basic-datatable").DataTable({
        processing: true,
        serverSide: true,
        ajax: {
            "url": "{% url 'master_petugas:datatable-json-role' %}",
            "headers": {
                "X-Requested-With": "XMLHttpRequest",
                "X-CSRFToken": '{{csrf_token}}',
            },
            "type": "POST"
        },
        bInfo : false,
        lengthMenu: [5, 25, 50, 100,'All'],
        columns :[
            {"data": 'jabatan'},
            {"data" : 'aksi'},
        ], 
        columnDefs: [ {
            'targets': [1], /* column index */
            'orderable': false, /* true or false */
            'className': "text-center"
        }],
        keys: !0,
        language: {
            paginate: {
            previous: "<i class='mdi mdi-chevron-left'>",
            next: "<i class='mdi mdi-chevron-right'>",
            },
        },
        drawCallback: function () {
            $(".dataTables_paginate > .pagination").addClass("pagination-rounded");
        },
    });

    function resetForm(){
        $('#formRolePetugas')[0].reset();
        $('.was-validated').removeClass('was-validated')
        $('#submitformRolePetugas').html('Kirim Data')
        $('#formRolePetugas').attr('action', "{% url 'master_petugas:role' %}")
        
    }

    function editRole(e){
      
        $('#formRolePetugas').attr('action', "{% url 'master_petugas:update-role' %}")
        $('#submitformRolePetugas').html('Update Data')
        
      
        $.ajax({
            url: '{% url 'master_petugas:detail-role' %}',
            type: "POST",
            dataType: "json",
            data : {
                'id' : e
            },
            headers: {
                "X-Requested-With": "XMLHttpRequest",
                "X-CSRFToken": '{{csrf_token}}',
            },
            success: (data) => {

                if (data.status == 'failed'){
                    Swal.fire(
                        'Terjadi Kesalahan!',
                         data.message,
                        'info'
                    )
                }else{
                    for (const [key, value] of Object.entries(data.instance)) {
                        $('#id_'+key).val(value)
                    }
                    $('.nav-tabs a[href="#input-tab"]').tab('show');
                    table.ajax.reload();
                }

            },
            error: (error) => {
                console.log(error);
            }
        });
    }

    function deleteRole(e){
        swalWithBootstrapButtons.fire({
            title: 'Are you sure?',
            text: "Apakah anda yakin ingin menghapus data role mitra?",
            icon: 'question',
            showCancelButton: true,
            confirmButtonText: 'Yes, delete it!',
            cancelButtonText: 'No, cancel!',
            reverseButtons: false
          }).then((result) => {
            if (result.isConfirmed) {

                $.ajax({
                    url: '{% url 'master_petugas:delete-role' %}',
                    type: "POST",
                    dataType: "json",
                    data : {
                        'id' : e
                    },
                    headers: {
                        "X-Requested-With": "XMLHttpRequest",
                        "X-CSRFToken": '{{csrf_token}}',
                    },
                    success: (data) => {

                        if (data.status == 'success'){
                            Swal.fire(
                                'Deleted!',
                                data.message,
                                'success'
                                )
                            table.ajax.reload();
                        }else{
                            Swal.fire(
                                'Terjadi Kesalahan!',
                                 data.message,
                                'info'
                            )
                        }
                    },
                    error: (error) => {
                        console.log(error);
                    }
                });
            }
        }) 
    }

    $('#formRolePetugas').on('submit', function(e){

        e.preventDefault()
        
        var serializedData = $(this).serialize();
        $('.invalid-feedback').html('')
        $('.is_invalid').removeClass('is_invalid')
        
        $.ajax({
            type: 'POST',
            url: $(this).attr('action'),
            data: serializedData,
            success: function (response) {

                $('#messages-content').html(response["message"])
                $('#msgs-upload').removeClass('alert-danger')
                $('#msgs-upload').addClass('alert-success')
                $('#msgs-upload').removeClass('d-none')
                resetForm()
                table.ajax.reload();

                $('.nav-tabs a[href="#rolepetugas-preview"]').tab('show');
            },
            error: function (response) {
                var errors = response["responseJSON"]["error"]
                for (const [key, value] of Object.entries(errors)) {
                    var msgs = '<ul>'
                    value.forEach(function (item, index) {
                    
                        msgs += '<li>'+item+'</li>'
                        });
                    
                    msgs += '</ul>'
                    $('#id_'+ key).addClass('is-invalid');
                    $('#msg-id_'+key).html(msgs)
                }    
                
            }
        })
    })

    $('#redraw-table').on('click', function (){
        table.draw();
    })

    $('#ResetformRolePetugas').on('click', function(e){
        resetForm()
    })


</script>

{% endblock tables-script-extend %}