authentication/urls.py
from django.urls import path
from . import views

app_name = 'auth'
urlpatterns = [
    path('user-profile/', views.UserThemeSetClassView.as_view(), name='user-profile'),
    path('account/', views.UserAccountClassView.as_view(), name='user-account'),

    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    # path('', views.UserThemeSetClassView.as_view(), name='user-theme')
]

munapps/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('authentication.urls')),
    # path('', include('home.urls')),
    
    path('', include('dashboard.urls')),
    path('', include('master_penilaian.urls')),
    path('', include('master_petugas.urls')),
    path('', include('master_survey.urls')),
    
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):

    theme_dark = (
       ('0', 'true'),
       ('1', 'false')
    )
        
    user = models.OneToOneField(User, on_delete=models.CASCADE) # Delete profile when user is deleted
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')
    theme = models.CharField(max_length=1, choices=theme_dark, default='1', null=False, blank=False, verbose_name='User Theme Dark Mode' )
    theme_condense = models.CharField(max_length=1, choices=theme_dark, default='1', null=False, blank=False, verbose_name='User Theme Left Side Condense' )
    
    def __str__(self):
        return f'{self.user.username} Profile' #show how we want it to be displayed

    def save(self):
        super().save()

        img = Image.open(self.image.path) # Open image

        # resize image
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size) # Resize image
            img.save(self.image.path) # Save it again and override the larger image

# Create your models here.
    
def create_profile(sender, instance, created, **kwargs):
    if created:
        user_profile = Profile(user=instance)
        user_profile.save()

post_save.connect(create_profile, sender=User)

authentication/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

# Create a ProfileUpdateForm to update image.
class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']
        labels = {
            'image' : 'Choose Picture Profile:', 
        }

        attrs_input = {
            'class' : 'form-control form-control-sm',
        }

        widgets = {
            'image': forms.FileInput(
                attrs = attrs_input,
            ),
          
        }

authentication/views.py
from django.shortcuts import render
from django.views import View

from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.conf import settings

from . import models
from . import forms

# Superuser account
# username: rifki.gusti
# password: hbz934115

class LoginView(LoginView):
    template_name = 'authentication/login.html'
    redirect_authenticated_user = True
    extra_context = {
        'title' : 'Login Page'
    }

class LogoutView(LogoutView):
    next_page = settings.LOGIN_URL
    extra_context = {
        'page_header' : 'Halaman Login'
    }


class UserThemeSetClassView(LoginRequiredMixin, View):

    def post(self, request):
        is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'

        if is_ajax:

            data = request.POST

            model = models.Profile.objects.get(user = request.user.id)

            if data.get('theme_dark'):
                model.theme = '1' if model.theme == '0' else '0'

            if data.get('condense_menu'):
                model.theme_condense = '1' if model.theme_condense == '0' else '0'
           
            model.save()   
            
            # send to client side.
            return JsonResponse({"status": 'success', 'message': 'Data berhasil diubah'}, status=200)
        
        return JsonResponse({"error": ""}, status=400)
    

class UserAccountClassView(LoginRequiredMixin, View):

    def get(self, request):
        context = {
            'title' : 'User Account',
            'form' : forms.ProfileUpdateForm(),
            'users_groups' : ', '.join(request.user.groups.values_list('name',flat = True))
        }
    
        return render(request, 'authentication/account.html', context)
    

    def post(self, request):
        is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'

        if is_ajax:
            form = forms.ProfileUpdateForm(request.FILES)
            if form.is_valid():
                model = models.Profile.objects.get(user = self.request.user.id)
                model.image = form.data.get('image')
                model.save()

                return JsonResponse({"status": "success", 'message':'Data berhasil diupdate'}, status=200)

        return JsonResponse({"status": "failed", "message" : 'Request needed'}, status=400)

authentication/templates/authentication/account.html
{% extends 'base/detached-layout/datables.html' %}
{% load static %}

{% block nav_content %}
<!-- start page title -->
<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="javascript: void(0);">Authentication</a></li>
                    <li class="breadcrumb-item">User Account</li>
                    <li class="breadcrumb-item">{{request.user.get_full_name}}</li>
                </ol>
            </div>
            <h4 class="page-title">{{title}}</h4>
        </div>
    </div>  
</div>     

{% endblock nav_content %}


{% block table-content %}

<div class="row">
    <div class="col-sm-12">
        <!-- Profile -->
        <div class="alert alert-dismissible border-0 fade show fade d-none" role="alert" id="upload_profile_pic">
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            <div id="upload_profile_pic_msg"></div>
        </div>

        <div class="alert alert-danger alert-dismissible border-0 fade d-none" role="alert" id="access_admin_site">
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            You dont have access to visit <strong>Administrator Site</strong>.
        </div>

        <div class="card bg-primary">
            <div class="card-body profile-user-box">
                <div class="row">
                    <div class="col-sm-8">
                        <div class="row align-items-center">
                            <div class="col">
                                <div>
                                    <h4 class="mt-1 mb-1 text-white">{{request.user.get_full_name}}</h4>
                                    <p class="font-13 text-white">Login as {{users_groups}}</p>

                                    <ul class="mb-0 list-inline text-light">
                                        <li class="list-inline-item me-3">
                                            <h5 class="mb-1 font-13 text-white">{{request.user.username}}</h5>
                                            <p class="mb-0 font-13 text-white-50">Username Account</p>
                                        </li>
                                        <li class="list-inline-item">
                                            <h5 class="mb-1 font-13 text-white">{{request.user.email}}</h5>
                                            <p class="mb-0 font-13 text-white-50">Email Account</p>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div> <!-- end col-->

                    <div class="col-sm-4">
                        <div class="text-center mt-sm-0 mt-3 text-sm-end">
                            {% if user.is_staff  %}
                                <a class="btn btn-light btn-disabled" href="/admin">
                                    <i class="mdi mdi-account-edit me-1"></i>Administrator Site
                                </a>
                            {% else %}
                                <button type="button" class="btn btn-light btn-disabled" id="toggleAlert">
                                    <i class="mdi mdi-account-edit me-1"></i>Administrator Site
                                </button>
                            {% endif %}


                        </div>
                    </div> <!-- end col-->
                </div> <!-- end row -->

            </div> <!-- end card-body/ profile-user-box-->

            <div class="card-footer">
                <div class="row mt-2">
                    <div class="col-md-4">
                        <form action="{% url 'auth:user-account' %}" id="profile-picture">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="{{form.image.id_for_label}}" class="form-label">{{ form.image.label }}</label>
                                {{form.image}}
                            </div>
                            <button type="submit" class="btn btn-primary btn-sm">Upload Picture</button>
                        </form>
                       
                    </div>
                </div>
            </div>
        </div><!--end profile/ card -->

    </div> <!-- end col-->
</div>
<!-- end row -->

{% endblock table-content %}

{% block tables-script-extend %}

<script>
    $('#toggleAlert').click(function(){
   
        $('#access_admin_site').removeClass('d-none')
        $('#access_admin_site').addClass('show')
    })

    $('#profile-picture').submit(function(e){

        e.preventDefault();
        var data = new FormData();
        data.append("image", $('#id_image').get(0).files[0])

        $.ajax({
            url: '{% url 'auth:user-account' %}',
            type: 'POST',
            data: data,
            processData: false,
            contentType: false,
            headers: {
                "X-Requested-With": "XMLHttpRequest",
                "X-CSRFToken": '{{csrf_token}}',
            },
            success: function (data) {
                if (data.status == 'success'){
                    $('#upload_profile_pic').addClass('alert-success')
                    $('#upload_profile_pic').removeClass('alert-danger')
                    $('#upload_profile_pic').removeClass('d-none')
                    $('#upload_profile_pic_msg').html(data.message)
                    location.reload();
                }else{
                    $('#upload_profile_pic').removeClass('alert-success')
                    $('#upload_profile_pic').addClass('alert-danger')
                    $('#upload_profile_pic').removeClass('d-none')
                    $('#upload_profile_pic_msg').html(data.message)
                }
            },
            error: function (xhr, status, error) {
                return console.log(xhr.responseText['messages'])
            }
        })

    })
</script>
{% endblock tables-script-extend %}

authentication/templates/authentication/login copy.html
{% load static %}
{% load widget_tweaks %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>{{ title }}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description" />
        <meta content="Coderthemes" name="author" />
        <!-- App favicon -->
        <link rel="shortcut icon" href="{% static 'app-design/assets/images/favicon.ico' %}">
        
        <!-- App css -->
    
        <link href="{% static 'app-design/assets/css/icons.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'app-design/assets/css/app.min.css' %}" rel="stylesheet" type="text/css" id="light-style" />
        <link href="{% static 'app-design/assets/css/app-dark.min.css' %}" rel="stylesheet" type="text/css" id="dark-style" />

    </head>

    <body class="loading authentication-bg" data-layout-config='{"leftSideBarTheme":"dark","layoutBoxed":false, "leftSidebarCondensed":false, "leftSidebarScrollable":false,"darkMode":false, "showRightSidebarOnStart": true}'>
        <div class="account-pages pt-2 pt-sm-5 pb-4 pb-sm-5">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-xxl-4 col-lg-5">
                        <div class="card">

                            <!-- Logo -->
                            <div class="card-header pt-4 pb-4 text-center bg-primary">
                                <a href="index.html">
                                    <span><img src="assets/images/logo.png" alt="" height="18"></span>
                                </a>
                            </div>

                            <div class="card-body p-4">
                                
                                <div class="text-center w-75 m-auto">
                                    <h4 class="text-dark-50 text-center pb-0 fw-bold">Sign In</h4>
                                    <p class="text-muted mb-4">Enter your username and password to access the application.</p>
                                </div>

                                <form method="POST" action="{% url 'auth:login' %}">
                                    
                                    {% csrf_token %}

                                    {% if form.errors %}
                                        {% for field, errors in form.errors.items %}
                                            {% for error in errors  %}
                                                <div class="alert alert-danger">
                                                    <strong>{{ error|escape }}</strong>
                                                </div>
                                            {% endfor %}
                                        {% endfor %}
                                    {% endif %}
                                    <div class="mb-3">
                                        <label for="{{ form.username.id_for_label }}" class="form-label">Username</label>
                                        {% render_field form.username class="form-control" type="text" id="{{ form.username.id_for_label }}" required="required" placeholder="Enter your username" %}
                                    </div>

                                    <div class="mb-3">
                                        <a href="pages-recoverpw.html" class="text-muted float-end"><small>Forgot your password?</small></a>
                                        <label for="password" class="form-label">Password</label>
                                        <div class="input-group input-group-merge">
                                            {% render_field form.password class="form-control" id="password" placeholder="Enter your password" %}
                                            <div class="input-group-text" data-password="false">
                                                <span class="password-eye"></span>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="mb-3 mb-3">
                                        <div class="form-check">
                                            <input type="checkbox" class="form-check-input" id="checkbox-signin" checked>
                                            <label class="form-check-label" for="checkbox-signin">Remember me</label>
                                        </div>
                                    </div>

                                    <div class="mb-3 mb-0 text-center">
                                        <button class="btn btn-primary" type="submit"> Log In </button>
                                    </div>

                                </form>
                            </div> <!-- end card-body -->
                        </div>
                        <!-- end card -->

                        <div class="row mt-3">
                            <div class="col-12 text-center">
                                <p class="text-muted">Don't have an account? <a href="pages-register.html" class="text-muted ms-1"><b>Sign Up</b></a></p>
                            </div> <!-- end col -->
                        </div>
                        <!-- end row -->

                    </div> <!-- end col -->
                </div>
                <!-- end row -->
            </div>
            <!-- end container -->
        </div>
        <!-- end page -->

        <footer class="footer footer-alt">
            2018 - 2021 © Made in love with inner beauty
        </footer>

        <!-- bundle -->
        <script src="{% static 'app-design/assets/js/vendor.min.js' %}"></script>
        <script src="{% static 'app-design/assets/js/app.min.js' %}"></script>
        
    </body>
</html>

authentication/templates/authentication/login.html
{% load static %}
{% load widget_tweaks %}


<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8" />
        <title>{{ title }}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description" />
        <meta content="Sistem Catatan dan Penilaian Mitra BPS Kabupaten Muna" name="Rifki Gustiawan" />
        <!-- App favicon -->

        <link rel="shortcut icon" href="{% static 'customs/img/bps.ico' %}">
  
        <!-- App css -->
    
        <link href="{% static 'app-design/assets/css/icons.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'app-design/assets/css/app.min.css' %}" rel="stylesheet" type="text/css" id="light-style" />
        <link href="{% static 'app-design/assets/css/app-dark.min.css' %}" rel="stylesheet" type="text/css" id="dark-style" />

    </head>

    <body class="authentication-bg pb-0" data-layout-config='{"darkMode":false}'>

        <div class="auth-fluid" style="
        background: url('{% static 'customs/img/bg-auth1.jpg' %}') right center !important; background-repeat : no-repeat !important;
        ">
            <!--Auth fluid left content -->
            <div class="auth-fluid-form-box">
                <div class="align-items-center d-flex h-100">
                    <div class="card-body">
                        <!-- Logo -->
                
                        <h4 class="mt-0">Selamat Datang Di Aplikasi</h4>
                        <h3>
                            <i>Sistem Catatan dan Penilaian Mitra BPS Kabupaten Muna</i>
                        </h3>
                        <!-- title-->
                
                        <h4 class="mt-4">Sign In</h4>
                        <p class="text-muted mb-4">Enter username and password to access account.</p>

                        <!-- form -->
                        <form method="POST" action="{% url 'auth:login' %}">
                                                                
                            {% csrf_token %}

                            {% if form.errors %}
                                {% for field, errors in form.errors.items %}
                                    {% for error in errors  %}
                                        <div class="alert alert-danger">
                                            <strong>{{ error|escape }}</strong>
                                        </div>
                                    {% endfor %}
                                {% endfor %}
                            {% endif %}

                            <div class="mb-3">
                                <label for="{{ form.username.id_for_label }}" class="form-label">Username</label>
                                {% render_field form.username class="form-control" type="text" id="{{ form.username.id_for_label }}" required="required" placeholder="Enter your username" %}
                            </div>
                            <div class="mb-3">
                                <label for="{{ form.username.id_for_password }}" class="form-label">Password</label>
                                <div class="input-group input-group-merge">
                                    {% render_field form.password class="form-control" id="password" placeholder="Enter your password" %}
                                    <div class="input-group-text" data-password="false">
                                        <span class="password-eye"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="d-grid mb-0 text-center">
                                <button class="btn btn-primary" type="submit"><i class="mdi mdi-login"></i> Log In </button>
                            </div>

                        </form>
                        <!-- end form-->

                    </div> <!-- end .card-body -->
                </div> <!-- end .align-items-center.d-flex.h-100-->
            </div>
            <!-- end auth-fluid-form-box-->

            <!-- Auth fluid right content -->
            <div class="auth-fluid-right text-center">
                <div class="auth-user-testimonial">
                    <h3 class="mb-3"><i class="mdi mdi-format-quote-open"></i> <i>Sistem Catatan dan Penilaian Mitra BPS Kabupaten Muna</i> <i class="mdi mdi-format-quote-close"></i></h3>
  
                    <p>
                        - BPS Kabupaten Muna
                    </p>
                </div> <!-- end auth-user-testimonial-->
            </div>
            <!-- end Auth fluid right content -->
        </div>
        <!-- end auth-fluid-->

        <!-- bundle -->
        <script src="{% static 'app-design/assets/js/vendor.min.js' %}"></script>
        <script src="{% static 'app-design/assets/js/app.min.js' %}"></script>

    </body>

</html>