home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    # path('', views.UserThemeSetClassView.as_view(), name='user-theme')
]

master_penilaian/urls.py
from django.urls import path
from . import views

app_name = 'master_penilaian'

urlpatterns = [
    path('master-penilaian', views.PenilaianPetugasClassView.as_view(), name='index'),
    path('master-penilaian/json-response', views.MasterPenilaianJsonResponseClassView.as_view(), name='datatable-json'),
    path('master_penilaian/delete', views.MasterPenilaianDeleteView.as_view(), name='delete-kegiatan'),
    path('master_penilaian/detail', views.MasterPenilaianDetailView.as_view(), name='detail-kegiatan'),
    path('master_penilaian/update', views.MasterPenilaianUpdateView.as_view(), name='update-kegiatan'),
    path('master_penilaian/export', views.MasterPenilaianExportView.as_view(), name='export-kegiatan'),
    path('master_penilaian/get-penilaian-by-survey', views.PenilaianGetBySurveiClassView.as_view(), name='get-penilaian-by-survei'),
    path('master_penilaian/get-alokasi-by-survey', views.AlokasiGetBySurveiClassView.as_view(), name='get-alokasi-by-survei'),

    path('nilai-mitra', views.NilaiMitraClassView.as_view(), name='nilai-mitra'),
    path('nilai-mitra/json-response', views.NilaiMitraJsonResponseClassView.as_view(), name='nilai-mitra-json'),
    path('nilai-mitra/delete', views.NilaiMitraDeleteClassView.as_view(), name='delete-nilai-mitra'),
    path('nilai-mitra/detail', views.NilaiMitraDetailClassView.as_view(), name='detail-nilai-mitra'),
    path('nilai-mitra/update', views.NilaiMitraUpdateClassView.as_view(), name='update-nilai-mitra'),
    path('nilai-mitra/export', views.NilaiMitraExportClassView.as_view(), name='export-nilai-mitra'),
    path('nilai-mitra/template/<int:kegiatan>', views.NilaiMitraTemplateClassView.as_view(), name='template-nilai-mitra'),
    path('nilai-mitra/upload', views.NilaiMitraUploadClassView.as_view(), name='upload-nilai-mitra'),
    path('nilai-mitra/table', views.GenerateTableNilaiClassView.as_view(), name='generate-table-nilai'),
    path('nilai-mitra/get-nilai-mitra', views.GetNilaiMitraClassView.as_view(), name='get-nilai-mitra'),
    

    path('indikator-penilaian', views.IndikatorPenilaianClassView.as_view(), name='indikator-penilaian'),
    path('indikator-penilaian/json-response', views.IndiakatorPenilaianJsonResponseClassView.as_view(), name='indikator-penilaian-json'),
    path('indikator-penilaian/delete', views.IndikatorPenilaianDeleteView.as_view(), name='delete-indikator'),
    path('indikator-penilaian/detail', views.IndikatorPenilaianDetailView.as_view(), name='detail-indikator'),
    path('indikator-penilaian/update', views.IndikatorPenilaianUpdateView.as_view(), name='update-indikator'),
    
    path('indikator-kegiatan', views.IndikatorKegiatanPenilaianClassView.as_view(), name='indikator-kegiatan'),
    path('indikator-kegiatan/json-response', views.IndikatorKegiatanPenilaianJsonResponseClassView.as_view(), name='indikator-kegiatan-json'),
    path('indikator-kegiatan/delete', views.IndikatorKegiatanPenilaianDeleteView.as_view(), name='delete-indikator-kegiatan'),
    path('indikator-kegiatan/detail', views.IndikatorKegiatanPenilaianDetailView.as_view(), name='detail-indikator-kegiatan'),
    path('indikator-kegiatan/update', views.IndikatorKegiatanPenilaianUpdateView.as_view(), name='update-indikator-kegiatan'),
    path('indikator-kegiatan/export', views.IndikatorKegiatanPenilaianExportView.as_view(), name='export-indikator-kegiatan'),
]

munapps/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('authentication.urls')),
    # path('', include('home.urls')),
    
    path('', include('dashboard.urls')),
    path('', include('master_penilaian.urls')),
    path('', include('master_petugas.urls')),
    path('', include('master_survey.urls')),
    
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

master_penilaian/models.py
from django.db import models
from master_survey.models import SurveyModel
from master_petugas.models import AlokasiPetugas, RoleMitra


# Create your models here.


class IndikatorPenilaian(models.Model):
   nama_indikator = models.CharField(max_length=128, null=False, blank=False, verbose_name='Indikator Penilaian' )
   deskripsi_penilaian = models.TextField(null=True, blank=True, verbose_name='Deskripsi Penilaian')

   def __str__(self):
      return f"{self.nama_indikator}"


class KegiatanPenilaianModel(models.Model):
   
    status = (
       ('0', 'Aktif'),
       ('1', 'Tidak Aktif')
    )

    nama_kegiatan = models.CharField(max_length=256, null=False, blank=False, verbose_name='Nama Kegiatan Penilaian' )
    survey = models.ForeignKey(SurveyModel, on_delete=models.RESTRICT, blank=False, null=False, related_name='penilaian_survei')
    tgl_penilaian = models.DateField( null=False, blank=False,  verbose_name='Tanggal Penilaian')
    status = models.CharField(max_length=1, choices=status, default=0, null=False, blank=False, verbose_name='Status Penilaian')
    role_permitted = models.ManyToManyField(RoleMitra)
    
    def __str__(self):
        return f"{self.nama_kegiatan} [{self.survey.nama}]"
   

class IndikatorKegiatanPenilaian(models.Model):
   kegiatan_penilaian = models.ForeignKey(KegiatanPenilaianModel, on_delete=models.RESTRICT, related_name='kegiatan_penilaian_petugas')
   indikator_penilaian = models.ForeignKey(IndikatorPenilaian, on_delete=models.RESTRICT, related_name='indikator_penilaian_petugas')
   
   def __str__(self):
      return f"{self.kegiatan_penilaian.nama_kegiatan} [{self.indikator_penilaian}]"


class MasterNilaiPetugas(models.Model):

   petugas = models.ForeignKey(AlokasiPetugas, on_delete=models.RESTRICT,  related_name='nilai_petugas')
   penilaian = models.ForeignKey(IndikatorKegiatanPenilaian, on_delete=models.RESTRICT, related_name='indikator_kegiatan_penilaian')
   nilai = models.SmallIntegerField(null=True, blank=True, verbose_name='Nilai Kegiatan Petugas')
   catatan = models.TextField(null=True, blank=True, verbose_name='Catatan Personal')

   def __str__(self):
      return f"{self.petugas.petugas.nama_petugas} [{self.penilaian.kegiatan_penilaian}]"
      

master_penilaian/views.py
import json
from pprint import pprint
from django.core.serializers.json import DjangoJSONEncoder

from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.shortcuts import render
from django.views import View
from django.core import serializers
from django.http import JsonResponse, HttpResponse
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from . import models
from . import forms
import string
import statistics

from django.urls import reverse_lazy
from django.shortcuts import redirect

from django.http import HttpResponse
from .resources import MasterNilaiResource, MasterKegiatanResource, IndikatorKegiatanResources

from master_petugas.models import RoleMitra, AlokasiPetugas
from master_survey.models import SurveyModel

import itertools
import numpy as np
from openpyxl import Workbook
from openpyxl.styles import Alignment
from openpyxl.styles import Font, PatternFill
from master_petugas import utils

class PenilaianPetugasClassView(LoginRequiredMixin, View):
    
    def get(self, request):
        context = {
            'title' : 'Kegiatan Penilaian',
            'data_survei' : SurveyModel.objects.all(),
            'data' : models.KegiatanPenilaianModel.objects.all(),
            'roles' : RoleMitra.objects.all(),
            'form' : forms.KegiatanPenilaianForm()
            }
    
        return render(request, 'master_penilaian/kegiatan_penilaian.html', context)


    def post(self, request):

        is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'
        if is_ajax:
            form = forms.KegiatanPenilaianForm(request.POST)
            if form.is_valid():
                instance = form.save()
                user_instance = serializers.serialize('json', [ instance, ])
                
                # send to client side.
                return JsonResponse({"instance": user_instance, 'message': 'Data berhasil ditambahkan'}, status=200)
            else:
                return JsonResponse({"error": form.errors}, status=400)
        return JsonResponse({"error": ""}, status=400)
    

class MasterPenilaianDeleteView(LoginRequiredMixin, View):

    def post(self, request):
        is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'

        if is_ajax:
            if request.method == 'POST':
                
                id = request.POST.get('id')

                data_petugas = models.KegiatanPenilaianModel.objects.filter(pk = id)
                if data_petugas.exists():

                    check_db = models.MasterNilaiPetugas.objects.filter(penilaian__kegiatan_penilaian = id)
                    if check_db.exists():
                        return JsonResponse({'status' : 'failed', 'message': 'Data kegiatan penilaian telah digunakan pada master data penilaian'}, status=200)
                
                    check_db_1 = models.IndikatorKegiatanPenilaian.objects.filter(kegiatan_penilaian = id)
                    if check_db_1.exists():
                        return JsonResponse({'status' : 'failed', 'message': 'Data kegiatan penilaian telah digunakan pada master data penilaian'}, status=200)
                    
                    data_petugas.delete()
                    return JsonResponse({'status' : 'success', 'message': 'Data berhasil dihapus'}, status=200)
                else:
                    return JsonResponse({'status': 'failed', 'message': 'Data tidak tersedia'}, status=200)
                
        return JsonResponse({'status': 'Invalid request'}, status=400)


class MasterPenilaianDetailView(LoginRequiredMixin, View):

    def post(self, request):
        is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'

        if is_ajax:
            if request.method == 'POST':
                
                id = request.POST.get('id')
                kegiatan_penilaian = get_object_or_404(models.KegiatanPenilaianModel, pk=id)

                context_data = {}
                context_data['id']              = kegiatan_penilaian.id
                context_data['nama_kegiatan']   = kegiatan_penilaian.nama_kegiatan
                context_data['survey_id']       = str(kegiatan_penilaian.survey.id)
                context_data['tgl_penilaian']   = kegiatan_penilaian.tgl_penilaian
                context_data['status']          = kegiatan_penilaian.status
                context_data['role_permitted']  = list(kegiatan_penilaian.role_permitted.values_list('id', flat=True))

                return JsonResponse({'status' : 'success', 'instance': context_data}, status=200)
                
        return JsonResponse({'status': 'Invalid request'}, status=400) 
    

class MasterPenilaianUpdateView(LoginRequiredMixin, View):

    def post(self, request):
        is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'
        if is_ajax:

            data = get_object_or_404(models.KegiatanPenilaianModel, pk=request.POST.get('id'))

            form = forms.KegiatanPenilaianForm(request.POST, instance=data)

            if form.is_valid():
                instance = form.save()
                ser_instance = serializers.serialize('json', [ instance, ])
                
                # send to client side.
                return JsonResponse({"instance": ser_instance, 'message': 'Data berhasil diubah'}, status=200)
            else:
                return JsonResponse({"error": form.errors}, status=400)
        return JsonResponse({"error": ""}, status=400)
    

class PenilaianGetBySurveiClassView(LoginRequiredMixin, View):

    def post(self, request):
        is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'

        if is_ajax:
            if request.method == 'POST':
                data = models.KegiatanPenilaianModel.objects.filter(survey=request.POST.get('survey_id')).values()
                return JsonResponse({"instance": list(data)}, status=200)
        
        return JsonResponse({"error": ""}, status=400)
    

class AlokasiGetBySurveiClassView(LoginRequiredMixin, View):
    
    def post(self, request):
        is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'

        if is_ajax:
            if request.method == 'POST':
                penilaian_id = int(request.POST.get('penilaian_id'))
                data = AlokasiPetugas.objects.filter(survey=request.POST.get('survey_id')).values('id', 'petugas__kode_petugas', 'petugas__nama_petugas', 'role', 'role__jabatan' )

                kegiatan_penilaian = get_object_or_404(models.KegiatanPenilaianModel, pk=penilaian_id)
                role_permitted = kegiatan_penilaian.role_permitted.values_list('id', flat=True)

                

                data_2 = models.IndikatorKegiatanPenilaian.objects.filter(kegiatan_penilaian = penilaian_id).values('id', 'indikator_penilaian__nama_indikator' )

                final_data = []
                for dt in data :

                    if dt['role'] in role_permitted:
                        db_check = models.MasterNilaiPetugas.objects.filter(petugas = dt['id'], penilaian__kegiatan_penilaian = penilaian_id)
                        if db_check.exists() == False:
                            final_data.append(dt)

                return JsonResponse({"instance": list(final_data), "instance_2": list(data_2)}, status=200)
        
        return JsonResponse({"error": ""}, status=400)


class MasterPenilaianJsonResponseClassView(LoginRequiredMixin, View):

    def post(self, request):    
        data_wilayah = self._datatables(request)
        return HttpResponse(json.dumps(data_wilayah, cls=DjangoJSONEncoder), content_type='application/json')
		
    def _datatables(self, request):
        datatables = request.POST
        
        # Get Draw
        draw = int(datatables.get('draw'))
        start = int(datatables.get('start'))
        length = int(datatables.get('length'))
        page_number = int(start / length + 1)

        search = datatables.get('search[value]')

        order_idx = int(datatables.get('order[0][column]')) # Default 1st index for
        order_dir = datatables.get('order[0][dir]') # Descending or Ascending
        order_col = 'columns[' + str(order_idx) + '][data]'
        order_col_name = datatables.get(order_col)

        if (order_dir == "desc"):
            order_col_name =  str('-' + order_col_name)

        data = models.KegiatanPenilaianModel.objects

        if datatables.get('survei_filter'):
            data = data.filter(survey = datatables.get('survei_filter'))
        
        if datatables.get('status_filter'):
            data = data.filter(status = datatables.get('status_filter'))

        if datatables.get('role_filter'):
            data = data.filter(role_permitted = datatables.get('role_filter'))

        data = data.all().exclude(Q(nama_kegiatan=None)|Q(survey=None)|Q(tgl_penilaian=None)|Q(status=None)|Q(role_permitted=None))
        records_total = data.count()
        records_filtered = records_total
        
        if search:
            data = models.KegiatanPenilaianModel.objects

            if datatables.get('survei_filter'):
                data = data.filter(survey = datatables.get('survei_filter'))
            
            if datatables.get('status_filter'):
                data = data.filter(status = datatables.get('status_filter'))

            if datatables.get('role_filter'):
                data = data.filter(role_permitted = datatables.get('role_filter'))

            data = data.filter(
                Q(nama_kegiatan__icontains=search)|
                Q(survey__nama__icontains=search)|
                Q(tgl_penilaian__icontains=search)|
                Q(status__icontains=search)|
                Q(role_permitted__jabatan__icontains=search)
            ).exclude(Q(nama_kegiatan=None)|Q(survey=None)|Q(sumber=None)|Q(tgl_penilaian=None)|Q(status=None)|Q(role_permitted=None))

master_penilaian/templates/master_penilaian/indikator_penilaian.html
{% extends 'base/detached-layout/datables.html' %}

{% load static %}

{% block nav_content %}
<!-- start page title -->
<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="javascript: void(0);">Manajemen Penilaian</a></li>
                    <li class="breadcrumb-item active">Indikator Penilaian</li>
                </ol>
            </div>
            <h4 class="page-title">{{title}}</h4>
        </div>
    </div>  
</div>     

{% endblock nav_content %}

{% block table-content %}

<div class="row">
    <div class="col-12">
        <div class="alert alert-danger d-none" id="msgs-upload" role="alert">   
           
            <div id="messages-content">
             
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="header-title">Indikator Penilaian</h4>
                <p class="text-muted font-14">
                    Indikator penilaian berisi informasi yang digunakan sebagai dasar penilaian mitra BPS Kabupaten Muna
                </p>
  
                <ul class="nav nav-tabs nav-bordered mb-3">
                      <li class="nav-item">
                          <a href="#indikator-penilaian-preview" data-bs-toggle="tab" aria-expanded="false" class="nav-link active">
                              Preview
                          </a>
                      </li>
                      <li class="nav-item">
                          <a href="#input-tab" data-bs-toggle="tab" aria-expanded="true" class="nav-link">
                              Input
                          </a>
                      </li>
                </ul> <!-- end nav-->
                <div class="tab-content">
                      <div class="tab-pane show active" id="indikator-penilaian-preview">
                            <div class="table-responsive">
                                <table id="basic-datatable" class="table table-centered table-striped w-100 dt-responsive nowrap">
                                    <thead>
                                        <tr>
                                            <th>Indikator Penilaian</th>
                                            <th>Deskripsi Penilaian</th>
                                            <th>Aksi</th> 
                                        </tr>
                                    </thead>
                                
                                    <tbody>
                                    </tbody>
                                </table>                                            
                            </div>
                      </div> <!-- end preview-->
                
                      <div class="tab-pane" id="input-tab">
                          <p>Silahkan isikan data Penilaian Peserta.</p>
                          <form action="{% url 'master_penilaian:indikator-penilaian' %}" method="POST" id="formKegiatanPenilaianPetugas" class="needs-validation" novalidate>
                            {% csrf_token %}
                            <input type="hidden" name="id" id="id_id">
                            <div class="row mt-3">
                                <div class="col-lg-6">
                                    <h5 class="mb-3">{{ form.nama_indikator.label }}</h5>
                                    <div class="form-floating errors" id="form_{{form.nama_indikator.id_for_label}}">
                                        {{form.nama_indikator}}
                                        <label for="{{form.nama_indikator.id_for_label}}">{{ form.nama_indikator.label }}</label>
                                        <div class="invalid-feedback" id="msg-{{form.nama_indikator.id_for_label}}">
                                        </div>
                                    </div>
                                </div>
                            
                                <div class="col-lg-6">
                                    <h5 class="mb-3">{{ form.deskripsi_penilaian.label }}</h5>
                                    <div class="form-floating errors" id="form_{{form.deskripsi_penilaian.id_for_label}}">
                                        {{form.deskripsi_penilaian}}
                                        <label for="{{form.deskripsi_penilaian.id_for_label}}">{{ form.deskripsi_penilaian.label }}</label>
                                   
                                    </div>
                                </div>
                            </div>
                            <br>
                            <div class="row mt-2">
                                <div class="col-lg">        
                                     <button type="submit" class="btn btn-primary" id="submitformIndikatorPenilaianPetugas">Kirim Data</button>
                                     <button type="button" class="btn btn-danger" id="ResetformIndikatorPenilaianPetugas">Reset</button>
                                </div>
                            </div>
                        
                        </form>
                      </div> <!-- end preview code-->
                </div> <!-- end tab-content-->
  
            </div> <!-- end card body-->
        </div> <!-- end card -->
    </div><!-- end col-->
</div>
  <!-- end row-->



{% endblock table-content %}

{% block tables-script-extend %}

<script>
    var swalWithBootstrapButtons = Swal.mixin({
        customClass: {
          confirmButton: 'btn btn-primary'},
        buttonsStyling: true
    })

    var table = $("#basic-datatable").DataTable({
        processing: true,
        serverSide: true,
        ajax: {
            "url": "{% url 'master_penilaian:indikator-penilaian-json' %}",
            "headers": {
                "X-Requested-With": "XMLHttpRequest",
                "X-CSRFToken": '{{csrf_token}}',
            },
            "type": "POST"
        },
        columns :[
            {"data": 'nama_indikator'},
            {"data": 'deskripsi_penilaian'},
            {"data" : 'aksi'},
        ],
        lengthMenu: [5, 25, 50, 100,'All'],
        columnDefs: [ {
            'targets': [2], /* column index */
            'orderable': false, /* true or false */
            'className': "text-center"
        }],
        keys: !0,
        language: {
            paginate: {
            previous: "<i class='mdi mdi-chevron-left'>",
            next: "<i class='mdi mdi-chevron-right'>",
            },
        },
        drawCallback: function () {
            $(".dataTables_paginate > .pagination").addClass("pagination-rounded");
        },
    });

    function resetForm(){
        $('#formKegiatanPenilaianPetugas')[0].reset();
        $('.was-validated').removeClass('was-validated')
        $('#submitformIndikatorPenilaianPetugas').html('Kirim Data')
        $('#formKegiatanPenilaianPetugas').attr('action', "{% url 'master_penilaian:index' %}")
    }

    function editIndikator(e){
        $('#formKegiatanPenilaianPetugas').attr('action', "{% url 'master_penilaian:update-indikator' %}")
        $('#submitformIndikatorPenilaianPetugas').html('Update Data')
    
        $.ajax({
            url: '{% url 'master_penilaian:detail-indikator' %}',
            type: "POST",
            dataType: "json",
            data : {
                'id' : e
            },
            headers: {
                "X-Requested-With": "XMLHttpRequest",
                "X-CSRFToken": '{{csrf_token}}',
            },
            success: (data) => {

                if (data.status == 'success'){

                    for (const [key, value] of Object.entries(data.instance)) {
                        $('#id_'+key).val(value)
                    }
                    $('.nav-tabs a[href="#input-tab"]').tab('show');
                    table.ajax.reload();

                }else{
                    Swal.fire(
                        'Terjadi Kesalahan!',
                         data.message,
                        'info'
                    )
                }
                
            },
            error: (error) => {
                console.log(error);
            }
        });
    }

    function deleteIndikator(e){

        swalWithBootstrapButtons.fire({
            title: 'Are you sure?',
            text: "Apakah anda yakin ingin menghapus indikator penilaian mitra?",
            icon: 'question',
            showCancelButton: true,
            confirmButtonText: 'Yes, delete it!',
            cancelButtonText: 'No, cancel!',
            reverseButtons: false
          }).then((result) => {
            if (result.isConfirmed) {
                
                $.ajax({
                    url: '{% url 'master_penilaian:delete-indikator' %}',
                    type: "POST",
                    dataType: "json",
                    data : {
                        'id' : e
                    },
                    headers: {
                        "X-Requested-With": "XMLHttpRequest",
                        "X-CSRFToken": '{{csrf_token}}',
                    },
                    success: (data) => {
        
                        if (data.status == 'success'){
                            Swal.fire(
                                'Deleted!',
                                data.message,
                                'success'
                                )
                            table.ajax.reload();
                        }else{
                            Swal.fire(
                                'Terjadi Kesalahan!',
                                 data.message,
                                'info'
                            )
                        }
                    },
                    error: (error) => {
                        console.log(error);
                    }
                });
            }
        }) 
        
    }
    
    $('#ResetformIndikatorPenilaianPetugas').on('click', function(e){
        resetForm()
    })

    $('#formKegiatanPenilaianPetugas').on('submit', function(e){

        e.preventDefault()
        
        var serializedData = $(this).serialize();
        $('.invalid-feedback').html('')
        $('.is_invalid').removeClass('is_invalid')
        $.ajax({
            type: 'POST',
            url: $(this).attr('action'),
            data: serializedData,
            success: function (response) {

                $('#messages-content').html(response["message"])
                $('#msgs-upload').removeClass('alert-danger')
                $('#msgs-upload').addClass('alert-success')
                $('#msgs-upload').removeClass('d-none')
                $(this)[0].reset();
                table.ajax.reload();

                $('.nav-tabs a[href="#indikator-penilaian-preview"]').tab('show');
            },
            error: function (response) {
                var errors = response["responseJSON"]["error"]
                for (const [key, value] of Object.entries(errors)) {
                    var msgs = '<ul>'
                    value.forEach(function (item, index) {
                    
                        msgs += '<li>'+item+'</li>'
                        });
                    
                    msgs += '</ul>'
                    $('#id_'+ key).addClass('is-invalid');
                    $('#msg-id_'+key).html(msgs)
                }    
            }
        })
    })
</script>

{% endblock tables-script-extend %}