dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.MainDashboardClassView.as_view(), name='index'),
    path('dashboard/ranking', views.DashboardRankClassView.as_view(), name='rank')
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    # path('', views.UserThemeSetClassView.as_view(), name='user-theme')
]

munapps/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('authentication.urls')),
    # path('', include('home.urls')),
    
    path('', include('dashboard.urls')),
    path('', include('master_penilaian.urls')),
    path('', include('master_petugas.urls')),
    path('', include('master_survey.urls')),
    
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
import json
from django.core.serializers.json import DjangoJSONEncoder
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.shortcuts import render

from django.db.models import Q
from master_petugas.models import MasterPetugas
from master_survey.models import SurveyModel
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from master_penilaian.models import KegiatanPenilaianModel, MasterNilaiPetugas
from django.http import JsonResponse, HttpResponse
from statistics import mean
from operator import itemgetter
from itertools import groupby

from django.urls import reverse_lazy

class MainDashboardClassView(LoginRequiredMixin, View):
    
    def get(self, request):

        context = {
            'title' : 'Dashboard',
            'mitra' : MasterPetugas.objects.all().count(),
            'mitra_block' : MasterPetugas.objects.filter(status =3).count(),
            'survey' : SurveyModel.objects.all().count(),
            'survey_finish' : SurveyModel.objects.filter(status = 2).count(),
            'penilaian' : KegiatanPenilaianModel.objects.all().count(),
            'penilaian_active' : KegiatanPenilaianModel.objects.filter(~Q(status = 1)).count(),
            'data_penilaian' : KegiatanPenilaianModel.objects.all(),
            'mitra_dinilai' : MasterNilaiPetugas.objects.values('petugas').distinct().count(),
            'nilai_mitra': MasterNilaiPetugas.objects.values('petugas', 'penilaian__kegiatan_penilaian').distinct().count(),
        }

        data = []

        db_nilai = MasterNilaiPetugas.objects.values('penilaian__indikator_penilaian__nama_indikator', 'nilai').order_by('penilaian__indikator_penilaian__nama_indikator')

        for idx, dt in enumerate(db_nilai):
  
            check_exist = [index for (index, d) in enumerate(data) if d["nama"] == dt['penilaian__indikator_penilaian__nama_indikator']]
            
            if len(check_exist) > 0:
                data[check_exist[0]]['data_series'].append(dt['nilai'])
                continue

            data.append({
                'nama' : dt['penilaian__indikator_penilaian__nama_indikator'],
                'rerata' : 0,
                'data_lain': '27%',
                'data_series': [dt['nilai'],],
            })

        data = data[:4]
        for idx, dt in enumerate(data):
            color = '#727cf5' if (idx+1) % 2 == 0 else '#0acf97'
            dt['rerata'] = round(float(mean(dt['data_series'])), 1)
            dt['min'] = round(float(min(dt['data_series'])), 1)
            dt['max'] = round(float(max(dt['data_series'])), 1)
            dt['color'] = color
            dt['data_series'] = dt['data_series'][-20:]
        
        context['summarize'] = data
        return render(request, 'dashboard/index.html', context)

class DashboardRankClassView(LoginRequiredMixin, View):

    def post(self, request):    
        data_wilayah = self._datatables(request)
        return HttpResponse(json.dumps(data_wilayah, cls=DjangoJSONEncoder), content_type='application/json')
		
    def _globalRank(self, request):
        data = MasterNilaiPetugas.objects.values('petugas__petugas__kode_petugas', 'petugas__petugas__nama_petugas', 'petugas__survey__nama', 'petugas__role__jabatan', 'penilaian__kegiatan_penilaian','penilaian__kegiatan_penilaian__nama_kegiatan', 'nilai')
        
        master_data = []
        
        for dt in data:
  
            check_exist = [index for (index, d) in enumerate(master_data) if d["kode_petugas"] == dt['petugas__petugas__kode_petugas']]
            
            if len(check_exist) > 0:

                check_exist_2 = [index for (index, d) in enumerate(master_data[check_exist[0]]['kegiatan_penilaian']) if d["id_kegiatan"] == dt['penilaian__kegiatan_penilaian']]
                
                if len(check_exist_2) > 0:
                    master_data[check_exist[0]]['kegiatan_penilaian'][check_exist_2[0]]['nilai'].append(dt['nilai'])
                else:
                    master_data[check_exist[0]]['kegiatan_penilaian'].append({
                        'id_kegiatan' : dt['penilaian__kegiatan_penilaian'],
                        'nama_kegiatan': dt['penilaian__kegiatan_penilaian__nama_kegiatan'],
                        'nilai' : [dt['nilai']]
                    })

                continue


            master_data.append({
                'kode_petugas': dt['petugas__petugas__kode_petugas'],
                'nama_petugas': dt['petugas__petugas__nama_petugas'],
                'rerata_final': 0,
                'ranking_final': 0,
                'kegiatan_penilaian' : [{'id_kegiatan': dt['penilaian__kegiatan_penilaian'] , 'nama_kegiatan': dt['penilaian__kegiatan_penilaian__nama_kegiatan'], 'nilai': [dt['nilai']]}]
            })

        for dt in master_data:
            
            mean_data = []
            for dt_kegiatan in dt['kegiatan_penilaian']:
                mean_data.append(round(mean(dt_kegiatan['nilai']), 2))
        
            dt['rerata_final'] = round(mean(mean_data), 2)

        data_sorted = sorted(master_data, key = itemgetter('rerata_final'), reverse=True)
        for idx, dt in enumerate(data_sorted):
            dt['ranking_final'] = idx+1

        return data_sorted


    def _datatables(self, request):


        datatables = request.POST
        
        # Get Draw
        draw = int(datatables.get('draw'))
        start = int(datatables.get('start'))
        length = int(datatables.get('length'))
        page_number = int(start / length + 1)

        search = datatables.get('search[value]')

        order_idx = int(datatables.get('order[0][column]')) # Default 1st index for
        order_dir = datatables.get('order[0][dir]') # Descending or Ascending
        order_col = 'columns[' + str(order_idx) + '][data]'
        order_col_name = datatables.get(order_col)

        if (order_dir == "desc"):
            order_col_name =  str('-' + order_col_name)


        data = MasterNilaiPetugas.objects
        if datatables.get('kegiatan_filter'):
            data = data.filter(penilaian__kegiatan_penilaian = datatables.get('kegiatan_filter'))

        data = data.values('petugas__petugas__id', 'petugas__petugas__kode_petugas', 'petugas__petugas__nama_petugas', 'petugas__survey__nama', 'petugas__role__jabatan', 'penilaian__kegiatan_penilaian__nama_kegiatan', 'nilai').exclude(Q(petugas=None)|Q(penilaian=None)|Q(nilai=None)|Q(catatan=None))

        records_total = data.count()
        records_filtered = records_total
    
        if search:
            data = MasterNilaiPetugas.objects

            if datatables.get('kegiatan_filter'):
                data = data.filter(penilaian__kegiatan_penilaian = datatables.get('kegiatan_filter'))

            data = data.filter(
                Q(petugas__petugas__kode_petugas__icontains=search)|
                Q(petugas__petugas__nama_petugas__icontains=search)|
                Q(petugas__role__jabatan__icontains=search)|
                Q(penilaian__kegiatan_penilaian__nama_kegiatan__icontains=search)
            ).values('petugas__petugas__id', 'petugas__petugas__kode_petugas', 'petugas__petugas__nama_petugas', 'petugas__survey__nama', 'petugas__role__jabatan', 'penilaian__kegiatan_penilaian__nama_kegiatan', 'nilai').exclude(Q(petugas=None)|Q(penilaian=None)|Q(nilai=None)|Q(catatan=None))
        
        if ('rerata' not in order_col_name) and ('ranking' not in order_col_name) and ('ranking_rerata' not in order_col_name) and ('ranking_final' not in order_col_name):
            data = data.order_by(order_col_name)

        data_df = []
        for dt in data:

            check_exist = [index for (index, d) in enumerate(data_df) if d["petugas__petugas__kode_petugas"] == dt['petugas__petugas__kode_petugas']]
            
            if len(check_exist) > 0:
                data_df[check_exist[0]]['rerata'].append(dt['nilai'])
                continue

            data_df.append({
                'petugas__petugas__id' : dt['petugas__petugas__id'],
                'petugas__petugas__kode_petugas': dt['petugas__petugas__kode_petugas'],
                'petugas__petugas__nama_petugas' : dt['petugas__petugas__nama_petugas'],
                'petugas__survey__nama': dt['petugas__survey__nama'],
                'petugas__role__jabatan' : dt['petugas__role__jabatan'],
                'penilaian__kegiatan_penilaian__nama_kegiatan': dt['penilaian__kegiatan_penilaian__nama_kegiatan'],
                'rerata' : [dt['nilai'],],
                'ranking': 0
            })

        for dt in data_df:
            dt['rerata'] = round(mean(dt['rerata']), 2)

        data_df = sorted(data_df, key = itemgetter('penilaian__kegiatan_penilaian__nama_kegiatan'))

        for key, value in groupby(data_df, key = itemgetter('penilaian__kegiatan_penilaian__nama_kegiatan')):

            dt_nilai = sorted(value, key=itemgetter('rerata'), reverse=True)
            for rank, k in enumerate(dt_nilai):
                k['ranking'] = rank+1


        global_ranking = self._globalRank(request)

        for dt in data_df:
            check_exist = [index for (index, d) in enumerate(global_ranking) if d["kode_petugas"] == dt['petugas__petugas__kode_petugas']]
            dt['rerata_final'] = global_ranking[check_exist[0]]['rerata_final']
            dt['ranking_final'] = global_ranking[check_exist[0]]['ranking_final']


        if 'rerata' in order_col_name:
            reverse = True if '-' in order_col_name else  False
            data_df = sorted(data_df, key=itemgetter('rerata'), reverse=reverse) 
        
        if 'ranking' in order_col_name:
            reverse = True if '-' in order_col_name else  False
            data_df = sorted(data_df, key=itemgetter('ranking'), reverse=reverse) 

        if 'rerata_final' in order_col_name:
            reverse = True if '-' in order_col_name else  False
            data_df = sorted(data_df, key=itemgetter('rerata_final'), reverse=reverse) 

dashboard/templates/dashboard/index.html
{% extends 'base/detached-layout/datables.html' %}

{% load static %}

{% block nav_content %}
<!-- start page title -->
<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="javascript: void(0);">Dashboard</a></li>
                    <li class="breadcrumb-item active">Dashboard</li>
                </ol>
            </div>
            <h4 class="page-title">{{title}}</h4>
        </div>
    </div>  
</div>     

{% endblock nav_content %}

{% block table-content %}

<div class="row">
    <div class="col-lg-6 col-xl-3">
        <div class="card tilebox-one">
            <div class="card-body">
                <i class='uil uil-users-alt float-end'></i> 
                <h6 class="text-uppercase mt-0">Active Mitra</h6>
                <h2 class="my-2" >{{mitra}}</h2>
                <p class="mb-0 text-muted">
                    <span class="text-success me-2"> {{mitra_block}}</span>
                    <span class="text-nowrap">Mitra Blacklist</span>  
                </p>
            </div> <!-- end card-body-->
        </div>
    </div>

    <div class="col-lg-6 col-xl-3">
        <div class="card tilebox-one">
            <div class="card-body">
                <i class='mdi mdi-clipboard-account-outline float-end'></i>
                <h6 class="text-uppercase mt-0">Active Survey</h6>
                <h2 class="my-2" >{{survey}}</h2>
                <p class="mb-0 text-muted">
                    <span class="text-success me-2"> {{survey_finish}}</span>
                    <span class="text-nowrap">Survei Selesai</span>  
                </p>
            </div> <!-- end card-body-->
        </div>
    </div>

    <div class="col-lg-6 col-xl-3">
        <div class="card tilebox-one">
            <div class="card-body">
                <i class="mdi mdi-clipboard-edit-outline float-end"></i>
                <h6 class="text-uppercase mt-0">Kegiatan Penilaian</h6>
                <h2 class="my-2" >{{penilaian}}</h2>
                <p class="mb-0 text-muted">
                    <span class="text-success me-2"> {{penilaian_active}}</span>
                    <span class="text-nowrap">Kegiatan Aktif</span>  
                </p>
            </div> <!-- end card-body-->
        </div>
    </div>

    <div class="col-lg-6 col-xl-3">
        <div class="card tilebox-one">
            <div class="card-body">
                <i class="mdi mdi-clipboard-check-multiple float-end"></i>
                <h6 class="text-uppercase mt-0">Penilaian Mitra</h6>
                <h2 class="my-2" >{{nilai_mitra}}</h2>
                <p class="mb-0 text-muted">
                    <span class="text-success me-2"> {{mitra_dinilai}}</span>
                    <span class="text-nowrap">Mitra Dinilai</span>  
                </p>
            </div> <!-- end card-body-->
        </div>
    </div>
</div>

<div class="row">
    
    {% for dt in summarize %}
        <div class="col-lg-6 col-xl-3">
            <div class="card">
                <div class="card-body">
                    <div class="row align-items-center">
                        <div class="col-6">
                            <h5 class="text-muted fw-normal mt-0 text-truncate" title="Rata-rata {{dt.nama}}">{{dt.nama}}</h5>
                            <h3 class="my-2 py-1">{{dt.rerata}}</h3>
                            <p class="mb-0 text-muted font-14">
                                <span class="text-success me-1" title="Nilai terendah {{dt.nama}}"><span class="mdi mdi-arrow-down-bold"></span> {{dt.min}}</span>
                            </p>
                            <p class="mb-0 text-muted font-14">
                                <span class="text-info me-2" title="Nilai tertinggi {{dt.nama}}"><span class="mdi mdi-arrow-up-bold"></span> {{dt.max}}</span>
                            </p>
                        </div>
                        <div class="col-6">
                            <div class="text-end">
                                <div id="campaign-sent-chart-{{ forloop.counter }}" data-colors="{{dt.color}}"></div>
                            </div>
                        </div>
                    </div> <!-- end row-->
                </div> <!-- end card-body -->
            </div> <!-- end card -->
        </div> <!-- end col -->
    {% endfor %}

</div>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                
                <div class="row mb-2">
                    <div class="col-sm-4">
                       <h5 class="text-uppercase mt-0">Penilaian Mitra Menurut Kegiatan </h5>
                    </div>
                    <div class="col-sm-8">
                        <div class="text-sm-end d-flex justify-content-end">
                            <select class="form-select mb-1" id="kegiatan_filter" name="kegiatan_filter" style="width:200px; height:40px">
                                <option value="">Kegiatan Penilaian</option>
                                {% for dt in data_penilaian  %}
                                    <option value="{{dt.id}}">{{dt.nama_kegiatan}}</option>
                                {% endfor %}
                             </select>&ensp;
                            <button type="button" class="btn btn-success mb-2 me-1" id="redraw-table"><i class="mdi mdi-refresh"></i></button>
                            <button type="button" class="btn btn-light mb-2" onclick="ExportToExcel('xlsx')">Export</button>
                        </div>
                    </div><!-- end col-->
                </div>
                
                <div class="table-responsive-sm">
                    <table class="table table-centered table-striped dt-responsive nowrap w-100" id="ranking-mitra">
                        <thead>
                            <tr>
                                <th>Nama</th>
                                <th>Jabatan</th>
                                <th>Kegiatan Penilaian</th>
                                <th>Mean</th>
                                <th>Rank</th>
                                <th>Global Mean</th>
                                <th>Global Rank</th>
                            </tr>
                        </thead>
                        <tbody>
                           
                        </tbody>
                    </table>
                </div>
            </div> <!-- end card-body-->
        </div> <!-- end card-->
    </div> <!-- end col -->
</div>


{% endblock table-content %}


{% block tables-script-extend %}

<script src="{% static 'app-design/assets/js/vendor/responsive.bootstrap5.min.js' %}"></script>

<!-- Apex js -->
<script src="{% static 'app-design/assets/js/vendor/apexcharts.min.js' %}"></script>

<!-- Todo js -->
<script src="{% static 'app-design/assets/js/ui/component.todo.js' %}"></script>

<script type="text/javascript" src="https://unpkg.com/xlsx@0.15.1/dist/xlsx.full.min.js"></script>

<script>

function ExportToExcel(type, fn, dl) {
    var elt = document.getElementById('ranking-mitra');
    var wb = XLSX.utils.table_to_book(elt, { sheet: "Ranking Mitra" });
    return dl ?
        XLSX.write(wb, { bookType: type, bookSST: true, type: 'base64' }):
        XLSX.writeFile(wb, fn || ('Data Ranking Mitra.' + (type || 'xlsx')));
    }

{% for dt in summarize  %}
    colors = ["#727cf5", "#0acf97", "#fa5c7c", "#ffbc00"];
    (dataColors = $("#campaign-sent-chart-{{ forloop.counter }}").data("colors")) &&
    (colors = dataColors.split(","));

    var series = [{data: []}]
    var labels = []

    {% for dt_series in dt.data_series %}
        series[0].data.push({{dt_series}})
        labels.push({{forloop.counter}})
    {% endfor %}

    var options = {
    chart: { type: "bar", height: 60, sparkline: { enabled: !0 } },
    plotOptions: { bar: { columnWidth: "60%" } },
    colors: colors,
    series: series,
    labels:labels,
    xaxis: { crosshairs: { width: 1 } },
    tooltip: {
        fixed: { enabled: !1 },
        x: { show: !1 },
        y: {
        title: {
            formatter: function (o) {
            return "";
            },
        },
        },
        marker: { show: !1 },
    },
    };
    new ApexCharts(document.querySelector("#campaign-sent-chart-{{ forloop.counter }}"), options).render();
{% endfor %}

var table = $("#ranking-mitra").DataTable({
    processing: true,
    serverSide: true,
    ajax: {
        "url": "{% url 'dashboard:rank' %}",
        "headers": {
            "X-Requested-With": "XMLHttpRequest",
            "X-CSRFToken": '{{csrf_token}}',
        },
        "data": function (d){
            return $.extend({}, d, {
                "kegiatan_filter": $('#kegiatan_filter').val(),
            })
        },
        "type": "POST"
    },

    lengthMenu: [5, 25, 50, 100],
    columns :[
        {"data": 'petugas__petugas__nama_petugas'},
        {"data": 'petugas__role__jabatan'},
        {"data" : 'penilaian__kegiatan_penilaian__nama_kegiatan'},
        {"data" : 'rerata'},
        {"data" : 'ranking'},
        {"data" : 'rerata_final'},
        {"data" : 'ranking_final'},
    ], 
    keys: !0,
    language: {
        paginate: {
        previous: "<i class='mdi mdi-chevron-left'>",
        next: "<i class='mdi mdi-chevron-right'>",
        },
    },
    drawCallback: function () {
        $(".dataTables_paginate > .pagination").addClass("pagination-rounded");
    },
});

$('#kegiatan_filter').bind("keyup change", function (){
    table.draw()
})

$('#redraw-table').on('click', function (){
    table.draw();
})

</script>

{% endblock tables-script-extend %}